# %RAML 1.0 NamedExample
EmpType:  
  -  
    "id": "1000"
    "fname": "Sanju"
    "lname": "Verma"
    "emailid": "myadd@email.com"
    "dob": "10-01-2000"
  -
    "id": "1010"
    "fname":  "Mohit"
    "lname":  "Burman"
    "emailid": "myadd@email.com"
    "dob": "10-01-2000"
  -
    "id": "1020"
    "fname":  "Vanita"
    "lname":  "Rimple"
    "emailid": "myadd@email.com"
    "dob": "10-01-2000"