#%RAML 1.0 NamedExample
type: object
properties:
  music: 
    type: object
    properties:
      collection?: string
      artists:
        type: object
        properties:
          artist1?: string
          artist2?: string
